-- Migration: Add Government Budget and State Inventory Tables
-- Date: 2024
-- Description: Adds state resource/product inventory and government budget transaction tracking

-- Add new transaction types to existing enum
ALTER TYPE "transaction_type" ADD VALUE IF NOT EXISTS 'state_resource_purchase';
ALTER TYPE "transaction_type" ADD VALUE IF NOT EXISTS 'state_resource_sale';
ALTER TYPE "transaction_type" ADD VALUE IF NOT EXISTS 'state_construction';

-- Create government budget transaction type enum
CREATE TYPE "government_budget_transaction_type" AS ENUM (
  'resource_purchase',
  'resource_sale',
  'construction',
  'tax_collection',
  'infrastructure',
  'military',
  'other'
);

-- State resource inventory table
CREATE TABLE IF NOT EXISTS "state_resource_inventory" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "state_id" INTEGER NOT NULL REFERENCES "states"("id") ON DELETE CASCADE,
  "resource_type" "resource_type" NOT NULL,
  "quantity" INTEGER NOT NULL DEFAULT 0,
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT "idx_state_resource" UNIQUE("state_id", "resource_type")
);

CREATE INDEX IF NOT EXISTS "idx_state_resource_state" ON "state_resource_inventory"("state_id");

-- State product inventory table
CREATE TABLE IF NOT EXISTS "state_product_inventory" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "state_id" INTEGER NOT NULL REFERENCES "states"("id") ON DELETE CASCADE,
  "product_type" "product_type" NOT NULL,
  "quantity" INTEGER NOT NULL DEFAULT 0,
  "updated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT "idx_state_product" UNIQUE("state_id", "product_type")
);

CREATE INDEX IF NOT EXISTS "idx_state_product_state" ON "state_product_inventory"("state_id");

-- Government budget transactions table
CREATE TABLE IF NOT EXISTS "government_budget_transactions" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "state_id" INTEGER NOT NULL REFERENCES "states"("id") ON DELETE CASCADE,
  "transaction_type" "government_budget_transaction_type" NOT NULL,
  "amount" BIGINT NOT NULL,
  "balance_after" BIGINT NOT NULL,
  "description" TEXT NOT NULL,
  "authorized_by" TEXT NOT NULL REFERENCES "account"("id") ON DELETE CASCADE,
  "item_type" VARCHAR(20),
  "item_name" VARCHAR(50),
  "quantity" INTEGER,
  "price_per_unit" BIGINT,
  "metadata" TEXT,
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_gov_transaction_state" ON "government_budget_transactions"("state_id");
CREATE INDEX IF NOT EXISTS "idx_gov_transaction_created_at" ON "government_budget_transactions"("created_at");
CREATE INDEX IF NOT EXISTS "idx_gov_transaction_state_created" ON "government_budget_transactions"("state_id", "created_at");

-- Add comments for documentation
COMMENT ON TABLE "state_resource_inventory" IS 'Tracks resources owned by state governments';
COMMENT ON TABLE "state_product_inventory" IS 'Tracks products owned by state governments';
COMMENT ON TABLE "government_budget_transactions" IS 'Tracks all government budget transactions including resource trading and construction';

COMMENT ON COLUMN "government_budget_transactions"."authorized_by" IS 'User who authorized the transaction (president or minister)';
COMMENT ON COLUMN "government_budget_transactions"."item_type" IS 'Type of item for trading transactions (resource or product)';
COMMENT ON COLUMN "government_budget_transactions"."item_name" IS 'Name of the item traded';
COMMENT ON COLUMN "government_budget_transactions"."quantity" IS 'Quantity of items in transaction';
COMMENT ON COLUMN "government_budget_transactions"."price_per_unit" IS 'Price per unit for trading transactions';
