-- Create broadcast_type enum
CREATE TYPE broadcast_type AS ENUM ('system', 'state', 'party');

-- Create broadcasts table (replaces per-user inbox broadcast messages)
CREATE TABLE broadcasts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broadcast_type broadcast_type NOT NULL,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    issued_by TEXT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    state_id INTEGER REFERENCES states(id) ON DELETE CASCADE,
    party_id INTEGER REFERENCES political_parties(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX idx_broadcast_active ON broadcasts (is_active);
CREATE INDEX idx_broadcast_state ON broadcasts (state_id, is_active);
CREATE INDEX idx_broadcast_party ON broadcasts (party_id, is_active);
CREATE INDEX idx_broadcast_type ON broadcasts (broadcast_type, is_active);
