-- Stock market: companies can go public via an explicit IPO action, issuing a
-- fixed share count. The founder's controlling block is locked (tracked in
-- company_shares, never listable); the remaining float trades on the same
-- listing/order-book model as the goods market.

-- New transaction_history types for share trades and dividend payouts.
-- ALTER TYPE ... ADD VALUE cannot run inside a transaction block; run these on their own.
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'share_purchase';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'share_sale';
ALTER TYPE transaction_type ADD VALUE IF NOT EXISTS 'dividend_payout';

CREATE TABLE IF NOT EXISTS company_shares (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_id integer NOT NULL UNIQUE REFERENCES companies(id) ON DELETE CASCADE,
	total_shares integer NOT NULL,
	founder_locked_shares integer NOT NULL,
	ipo_price bigint NOT NULL,
	ipo_at timestamp NOT NULL DEFAULT now(),
	last_dividend_at timestamp
);

CREATE TABLE IF NOT EXISTS share_holdings (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_id integer NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
	user_id text NOT NULL REFERENCES account(id) ON DELETE CASCADE,
	quantity integer NOT NULL DEFAULT 0,
	updated_at timestamp NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_share_holding_company_user ON share_holdings (company_id, user_id);
CREATE INDEX IF NOT EXISTS idx_share_holding_company ON share_holdings (company_id);

CREATE TABLE IF NOT EXISTS share_listings (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_id integer NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
	seller_id text NOT NULL REFERENCES account(id) ON DELETE CASCADE,
	quantity integer NOT NULL,
	price_per_unit bigint NOT NULL,
	created_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_share_listing_company ON share_listings (company_id);

CREATE TABLE IF NOT EXISTS share_transactions (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_id integer NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
	listing_id integer REFERENCES share_listings(id) ON DELETE SET NULL,
	buyer_id text NOT NULL REFERENCES account(id) ON DELETE CASCADE,
	seller_id text NOT NULL REFERENCES account(id) ON DELETE CASCADE,
	quantity integer NOT NULL,
	total_price bigint NOT NULL,
	completed_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_share_transaction_company ON share_transactions (company_id);

CREATE TABLE IF NOT EXISTS dividend_payouts (
	id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	company_id integer NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
	user_id text NOT NULL REFERENCES account(id) ON DELETE CASCADE,
	amount bigint NOT NULL,
	shares_held integer NOT NULL,
	paid_at timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_dividend_company ON dividend_payouts (company_id);
CREATE INDEX IF NOT EXISTS idx_dividend_user ON dividend_payouts (user_id);
