-- Create birthday_rewards table
-- Tracks which account anniversary (creation) years a user has collected.
CREATE TABLE IF NOT EXISTS birthday_rewards (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    year INTEGER NOT NULL,
    collected_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- One collection record per user per anniversary year.
CREATE UNIQUE INDEX IF NOT EXISTS idx_birthday_reward_user_year ON birthday_rewards (user_id, year);
