-- Migration: Add Bloc Leadership Tables
-- Description: Adds a persisted bloc leader (1 per bloc) and up to two diplomats per bloc

CREATE TABLE IF NOT EXISTS "bloc_leaders" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" TEXT NOT NULL REFERENCES "account"("id") ON DELETE CASCADE,
  "bloc_id" INTEGER NOT NULL UNIQUE REFERENCES "blocs"("id") ON DELETE CASCADE,
  "appointed_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "bloc_diplomats" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "user_id" TEXT NOT NULL REFERENCES "account"("id") ON DELETE CASCADE,
  "bloc_id" INTEGER NOT NULL REFERENCES "blocs"("id") ON DELETE CASCADE,
  "appointed_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT "idx_bloc_diplomat_unique" UNIQUE("user_id", "bloc_id")
);

CREATE INDEX IF NOT EXISTS "idx_bloc_diplomats_bloc" ON "bloc_diplomats"("bloc_id");
