-- Migration: Add Bloc Leader Elections
-- Description: Bloc leaders are now elected by the presidents of member states every
-- 30-day cycle. Presidents can nominate a citizen of any member state (not themselves)
-- during the final 2 days of the cycle, then vote for one of the nominated candidates.

CREATE TABLE IF NOT EXISTS "bloc_leader_elections" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "bloc_id" INTEGER NOT NULL REFERENCES "blocs"("id") ON DELETE CASCADE,
  "cycle_starts_at" TIMESTAMP NOT NULL,
  "voting_starts_at" TIMESTAMP NOT NULL,
  "voting_ends_at" TIMESTAMP NOT NULL,
  "status" election_status NOT NULL DEFAULT 'scheduled',
  "created_at" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "idx_bloc_leader_elections_bloc" ON "bloc_leader_elections"("bloc_id");

CREATE TABLE IF NOT EXISTS "bloc_leader_candidates" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "election_id" INTEGER NOT NULL REFERENCES "bloc_leader_elections"("id") ON DELETE CASCADE,
  "candidate_user_id" TEXT NOT NULL REFERENCES "account"("id") ON DELETE CASCADE,
  "nominated_by" TEXT NOT NULL REFERENCES "account"("id") ON DELETE CASCADE,
  "nominated_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT "idx_bloc_election_candidate" UNIQUE("election_id", "candidate_user_id")
);

CREATE TABLE IF NOT EXISTS "bloc_leader_votes" (
  "id" INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "election_id" INTEGER NOT NULL REFERENCES "bloc_leader_elections"("id") ON DELETE CASCADE,
  "voter_id" TEXT NOT NULL REFERENCES "account"("id") ON DELETE CASCADE,
  "candidate_user_id" TEXT NOT NULL REFERENCES "account"("id") ON DELETE CASCADE,
  "voted_at" TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT "idx_bloc_election_voter" UNIQUE("election_id", "voter_id")
);
