-- Migration: Add newspaper subscriptions and article views
-- This migration adds support for users to subscribe to newspapers and track article views

-- Create newspaper subscriptions table
CREATE TABLE IF NOT EXISTS newspaper_subscriptions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id TEXT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    newspaper_id INTEGER NOT NULL REFERENCES newspapers(id) ON DELETE CASCADE,
    subscribed_at TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_user_newspaper_subscription UNIQUE (user_id, newspaper_id)
);

-- Create indexes for newspaper subscriptions
CREATE INDEX IF NOT EXISTS idx_subscription_newspaper ON newspaper_subscriptions(newspaper_id);

-- Create article views table
CREATE TABLE IF NOT EXISTS article_views (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    user_id TEXT REFERENCES account(id) ON DELETE SET NULL,
    viewed_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create indexes for article views
CREATE INDEX IF NOT EXISTS idx_article_views_article ON article_views(article_id);
CREATE INDEX IF NOT EXISTS idx_article_views_viewed_at ON article_views(viewed_at);

-- Comments
COMMENT ON TABLE newspaper_subscriptions IS 'Tracks user subscriptions to newspapers';
COMMENT ON TABLE article_views IS 'Tracks views of articles for statistics (user_id can be null for anonymous views)';
