-- Migration: Add push notification subscriptions
-- Description: Adds table for storing Web Push API subscription data

-- Create push subscriptions table
CREATE TABLE IF NOT EXISTS push_subscriptions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id TEXT NOT NULL REFERENCES account(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL,
    p256dh_key TEXT NOT NULL,
    auth_key TEXT NOT NULL,
    user_agent TEXT,
    subscribed_at TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Create indexes
CREATE UNIQUE INDEX IF NOT EXISTS idx_push_endpoint ON push_subscriptions(endpoint);
CREATE INDEX IF NOT EXISTS idx_push_user ON push_subscriptions(user_id);

-- Add comments
COMMENT ON TABLE push_subscriptions IS 'Stores Web Push API subscription data for push notifications';
COMMENT ON COLUMN push_subscriptions.endpoint IS 'Unique push subscription endpoint URL';
COMMENT ON COLUMN push_subscriptions.p256dh_key IS 'Public key for message encryption (P-256 ECDH)';
COMMENT ON COLUMN push_subscriptions.auth_key IS 'Authentication secret for subscription';
COMMENT ON COLUMN push_subscriptions.user_agent IS 'User agent string of the subscribing device';
