// Cooldown configuration for various actions
export const COOLDOWNS_CONFIG = {
    PARTY_CREATION_DAYS: 7,
    PARTY_EDIT_HOURS: 24,
    COMPANY_CREATION_DAYS: 3,
    COMPANY_EDIT_HOURS: 24,
    FACTORY_CREATION_HOURS: 48,
    MARKET_LISTING_REMOVAL_HOURS: 1,
    STATE_EDIT_HOURS: 48,
    BLOC_ACTION_HOURS: 72,
    WORK_HOURS: 24,
    TRAVEL_MIN_HOURS: 1
} as const;

// Helper to convert cooldowns to milliseconds
export const COOLDOWNS_MS = {
    PARTY_CREATION: COOLDOWNS_CONFIG.PARTY_CREATION_DAYS * 24 * 60 * 60 * 1000,
    PARTY_EDIT: COOLDOWNS_CONFIG.PARTY_EDIT_HOURS * 60 * 60 * 1000,
    COMPANY_CREATION: COOLDOWNS_CONFIG.COMPANY_CREATION_DAYS * 24 * 60 * 60 * 1000,
    COMPANY_EDIT: COOLDOWNS_CONFIG.COMPANY_EDIT_HOURS * 60 * 60 * 1000,
    FACTORY_CREATION: COOLDOWNS_CONFIG.FACTORY_CREATION_HOURS * 60 * 60 * 1000,
    MARKET_LISTING_REMOVAL: COOLDOWNS_CONFIG.MARKET_LISTING_REMOVAL_HOURS * 60 * 60 * 1000,
    STATE_EDIT: COOLDOWNS_CONFIG.STATE_EDIT_HOURS * 60 * 60 * 1000,
    BLOC_ACTION: COOLDOWNS_CONFIG.BLOC_ACTION_HOURS * 60 * 60 * 1000,
    WORK: COOLDOWNS_CONFIG.WORK_HOURS * 60 * 60 * 1000
} as const;
