-- HOI4 Regions SQL Insert Statements
-- Generated from hoi4cheats.com
-- Total regions: 762
-- Generated at: 2025-12-26T16:34:07.143Z

BEGIN;

INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Italy');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Poland');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'France');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Spain');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Germany');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Poland');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Poland');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Poland');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Poland');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Poland');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Poland');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Poland');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Poland');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Poland');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Poland');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Italy');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Italy');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Italy');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Italy');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'UK');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Italy');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Italy');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Italy');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Italy');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Italy');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Italy');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Italy');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Spain');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Spain');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Spain');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Spain');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Spain');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Spain');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Spain');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Spain');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Spain');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Spain');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Spain');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USSR');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'USA');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications, country) VALUES (0, 0, 0, 0, 0, 0, 'Japan');
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO regions (rating, infrastructure, economy, education, hospitals, fortifications) VALUES (0, 0, 0, 0, 0, 0);

COMMIT;